eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8088
spring:
  application:
    name: product
  datasource:
    username: root
    password: 199639
    url: jdbc:mysql:///u4110?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.1.7
    username: guest
    password: guest
    port: 5672
